# the unit test file(s) should be placed inside a folder called test
name: main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# only one job  thgat does the following
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # Retrieve the code from our repository
    - name: Checkout
      uses: actions/checkout@v3

    # Download Node.js version 17 for GitHub Actions to run
    - name: Use Node 17.x
      uses: actions/setup-node@v3
      with:
        node-version: '17.x'
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    # Install the required dependencies
    - name: Install dependencies
      run: |
        npm install
        npm ci
      #run: npm ci --ignore-scripts

    # Run the tests
    - name: Test
      run: npm test
